Add Translation Portuguese of Brazil
katahiromz/RisohEditor pull request #167
Opened 2021-12-30 16:16 UTC by JNylson

2021-12-30 16:28 UTC, katahiromz requested changes

2021-12-30 16:28 UTC, katahiromz commented on src/lang/pt_BR.rc
> +        MENUITEM "Selecionar Idioma da Inte&rface (UI语言选择)...", ID_CHOOSEUILANG
Don't translate this line, please.

2021-12-30 18:05 UTC, JNylson commented
Fixed requested string

2021-12-30 23:12 UTC, JNylson commented on src/lang/pt_BR.rc
> +        MENUITEM "Selecionar Idioma da Inte&rface (UI语言选择)...", ID_CHOOSEUILANG
ok, i'm fixed requested string

2021-12-31 01:52 UTC, merged

2021-12-31 11:05 UTC, katahiromz commented
Thanks.